import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import { VitePWA } from 'vite-plugin-pwa';

export default defineConfig({
    plugins: [
        laravel({
            input: ['resources/css/app.css', 'resources/js/app.js'],
            refresh: true,
        }),
        // M15 — the service worker body is hand-written (resources/js/sw.js); the plugin only
        // swaps self.__WB_MANIFEST for the build's precache list. The manifest is generated by
        // Laravel from config/pwa.php instead (one source of truth, testable without a build),
        // and registration happens by hand in app.js against /sw.js — see PwaController for why
        // the worker is served from the app root rather than /build.
        VitePWA({
            strategies: 'injectManifest',
            srcDir: 'resources/js',
            filename: 'sw.js',
            injectRegister: false,
            manifest: false,
            injectManifest: {
                globDirectory: 'public/build',
                globPatterns: ['**/*.{js,css,woff2}'],
                // The glob yields paths relative to public/build ("assets/app-x.js"). The
                // worker is served from the app root, so those would resolve to /assets/…
                // and 404 — every precache entry silently lost. Prefix them to the real
                // public path.
                modifyURLPrefix: { '': '/build/' },
                // The worker precaches itself otherwise, pinning clients to a stale copy.
                globIgnores: ['sw.js', 'sw.mjs'],
            },
        }),
    ],
    server: {
        host: '0.0.0.0',
        hmr: {
            host: '192.168.29.67',
        },
    },
});
